### ISSUE TITLE
程序运行出错了,怎样改正？

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [XinzeZhang/DeepAR-torch#1]
@XinzeZhang,你好！
          在pycharm 中运行你的程序出现如下错误：

C:\Anaconda\envs\torch\python.exe F:/MsVsPython/ImportPytorchNet/OnlyDeepAR/4-XinzeZhang/DeepAR-torch-master/baseline.py
Traceback (most recent call last):
  File "F:/MsVsPython/ImportPytorchNet/OnlyDeepAR/4-XinzeZhang/DeepAR-torch-master/baseline.py", line 52, in <module>
    rmse, vrmse, pred, vpred = msvr.fit_validate(
  File "F:\MsVsPython\ImportPytorchNet\OnlyDeepAR\4-XinzeZhang\DeepAR-torch-master\model\MSVR.py", line 171, in fit_validate
    self.fit(x,y)
  File "F:\MsVsPython\ImportPytorchNet\OnlyDeepAR\4-XinzeZhang\DeepAR-torch-master\model\MSVR.py", line 88, in fit
    M1 = H[i1][:, i1] + \
MemoryError: Unable to allocate 2.87 GiB for an array with shape (19620, 19620) and data type float64

Process finished with exit code 1

怎样改正？

**Comment by XinzeZhang** [comment]
您好,

根据程序的报错，展示无法看出确切的故障原因。猜测可能是由于您的样本集很大，核函数计算之后的矩阵占用内存过多导致的。
能否麻烦您更换数据集或slice部分样本进行测试，观察能否重现此错误。

另外，能否给出您的Python环境，以便更好判断。


Sincerely


Xinze Zhang

------

Ph.D Candidate,

Centre for Modern Information Management & John Hopcroft Lab

Huazhong University of Science & Technology

On Mar 24, 2021, at 4:09 PM, 2017wxyzwxyz ***@***.******@***.***>> wrote:



@XinzeZhang<https://github.com/XinzeZhang>,你好！
在pycharm 中运行你的程序出现如下错误：

C:\Anaconda\envs\torch\python.exe F:/MsVsPython/ImportPytorchNet/OnlyDeepAR/4-XinzeZhang/DeepAR-torch-master/baseline.py
Traceback (most recent call last):
File "F:/MsVsPython/ImportPytorchNet/OnlyDeepAR/4-XinzeZhang/DeepAR-torch-master/baseline.py", line 52, in
rmse, vrmse, pred, vpred = msvr.fit_validate(
File "F:\MsVsPython\ImportPytorchNet\OnlyDeepAR\4-XinzeZhang\DeepAR-torch-master\model\MSVR.py", line 171, in fit_validate
self.fit(x,y)
File "F:\MsVsPython\ImportPytorchNet\OnlyDeepAR\4-XinzeZhang\DeepAR-torch-master\model\MSVR.py", line 88, in fit
M1 = H[i1][:, i1] +
MemoryError: Unable to allocate 2.87 GiB for an array with shape (19620, 19620) and data type float64

Process finished with exit code 1

怎样改正？

**Comment by 2017wxyzwxyz** [comment]
@XinzeZhang,你好！谢谢回复，代码完全是copy你的，没有丝毫更改。我的python是3.8.5，pytorch是1.7.1，请想想可能是什么原因造成出现这个错误？我debug运行，第一个错误出现在MSVR.py的88行‘M1 = H[i1][:, i1] + \’语句。
        另外请问你跑通过‘https://github.com/jingw2/demand_forecast’仓库中的deepar.py吗？

**Comment by XinzeZhang** [comment]
您好，您应该是在运行baseline.py文件中发生“MemoryError: Unable to allocate 2.87 GiB for an array with shape (19620, 19620) and data type float64”这个问题，在没有更改代码的情况下，MSVR的代码是没有问题的。
在计算MT_001数据集时，MSVR会占用非常高的内存，因此产生了内存溢出的问题。解决这个问题的方法在于升级您的电脑内存。

您提问的方式与语气还有很高的提升空间。我在不清楚您环境、运行哪个程序的情况下，因为能力有限，没有办法给出确切的回答和帮助的。因此还需要您自己想想可能是什么原因造成出现这个错误。

对于您的第二个问题，没有跑过，所以无法给予回答。
